org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.86

mod_id=computelib
mod_name=ComputeLib
mod_license=MIT License
mod_version=0.0
mod_group_id=dev.nonamecrackers2.computelib
